version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  auth:
    build: 
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: yarn run start:dev auth # overrides CMD from dockerfile

  messenger_api:
    build: 
      context: ./
      dockerfile: ./apps/messenger_api/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to the base folder should be reflected
      - /usr/src/app/node_modules
    command: yarn run start:dev api # overrides CMD from dockerfile

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'